// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMY-UDoD36xHZEpBUxstflXHzkA2EAe8',
    appId: '1:886370477326:web:3537e9bb67cf895bdf635f',
    messagingSenderId: '886370477326',
    projectId: 'pharmacare-73',
    authDomain: 'pharmacare-73.firebaseapp.com',
    storageBucket: 'pharmacare-73.firebasestorage.app',
    measurementId: 'G-TT2KLZWZMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGWgViZI-8_hQv8b2Pwn62EJfVJKjzUE',
    appId: '1:886370477326:android:abd237746ebf5fafdf635f',
    messagingSenderId: '886370477326',
    projectId: 'pharmacare-73',
    storageBucket: 'pharmacare-73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVq_CJLcjIdf0rpRw0hW3HUWQGsICQcQ',
    appId: '1:886370477326:ios:26126007ddfa9ca7df635f',
    messagingSenderId: '886370477326',
    projectId: 'pharmacare-73',
    storageBucket: 'pharmacare-73.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVq_CJLcjIdf0rpRw0hW3HUWQGsICQcQ',
    appId: '1:886370477326:ios:26126007ddfa9ca7df635f',
    messagingSenderId: '886370477326',
    projectId: 'pharmacare-73',
    storageBucket: 'pharmacare-73.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXMY-UDoD36xHZEpBUxstflXHzkA2EAe8',
    appId: '1:886370477326:web:613d6e514451dd39df635f',
    messagingSenderId: '886370477326',
    projectId: 'pharmacare-73',
    authDomain: 'pharmacare-73.firebaseapp.com',
    storageBucket: 'pharmacare-73.firebasestorage.app',
    measurementId: 'G-PT1HBM2XJL',
  );
}
